import Head from "next/head";
import { Inter } from "next/font/google";
// import styles from "./styles/Home.module.css";
import styles from "./styles.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NewBie Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="keywords"
          content="nextjs, newbie coder blog, newbie coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <span className={styles.logo}>newbieCoder</span>
        <ul className={styles.links}>
          <li>Home</li>
          <li>About</li>
          <li>Contact</li>
          <li>Blog</li>
        </ul>
      </nav>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.h1}>Newbie Coder</h1>
        <p className={styles.p}>
          This a Project by Newbie Coder - Abhishek Choudhary
        </p>
      </main>
    </>
  );
}
