import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NewBie Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="keywords"
          content="nextjs, newbie coder blog, newbie coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.h1}>Newbie Coder</h1>
        <p className={styles.p}>
          This is a Blogging Project by Newbie Coder - Abhishek Choudhary
        </p>
        <Image
          className={styles.homeImg}
          width={300}
          height={200}
          src="/home-bg.jpg"
          priority={true}
          alt="home-background"
        />
      </main>
    </>
  );
}
